from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    Integer,
    MetaData,
    String,
    Table,
    Text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID

metadata = MetaData()
uuid_type = UUID(as_uuid=True)

tenants = Table(
    "tenants",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("slug", String),
    Column("name", String),
    Column("status", String),
)
users = Table(
    "users",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("email", String),
    Column("password_hash", Text),
    Column("display_name", String),
    Column("status", String),
)
auth_refresh_sessions = Table(
    "auth_refresh_sessions",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("user_id", uuid_type),
    Column("token_hash", String),
    Column("expires_at", DateTime(timezone=True)),
    Column("revoked_at", DateTime(timezone=True)),
    Column("replaced_by_id", uuid_type),
    Column("user_agent", String),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)
memberships = Table(
    "memberships",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("user_id", uuid_type),
    Column("role", String),
    Column("status", String),
)
course_enrollments = Table(
    "course_enrollments",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("status", String),
)
courses = Table(
    "courses",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("slug", String),
    Column("title", String),
    Column("status", String),
    Column("exam_date", Date),
)
graph_versions = Table(
    "graph_versions",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("version", String),
    Column("status", String),
)
document_versions = Table(
    "document_versions",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("checksum", String),
    Column("source_type", String),
    Column("status", String),
    Column("title", String),
    Column("source_path", Text),
    Column("parser_version", String),
    Column("metadata", JSONB),
)
source_spans = Table(
    "source_spans",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("document_version_id", uuid_type),
    Column("locator", JSONB),
    Column("text", Text),
    Column("checksum", String),
)
chunks = Table(
    "chunks",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("source_span_id", uuid_type),
    Column("parent_chunk_id", uuid_type),
    Column("content", Text),
    Column("checksum", String),
    Column("is_active", Boolean),
    Column("chunk_type", String),
    Column("ordinal", Integer),
    Column("token_count", Integer),
    Column("metadata", JSONB),
)
concept_nodes = Table(
    "concept_nodes",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("graph_version_id", uuid_type),
    Column("canonical_name", String),
    Column("normalized_name", String),
    Column("node_type", String),
    Column("summary", Text),
    Column("exam_weight", Float),
    Column("confidence", Float),
    Column("extraction_method", String),
    Column("review_status", String),
    Column("evidence_source_span_id", uuid_type),
)
concept_edges = Table(
    "concept_edges",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("graph_version_id", uuid_type),
    Column("source_concept_id", uuid_type),
    Column("target_concept_id", uuid_type),
    Column("relation_type", String),
    Column("weight", Float),
    Column("confidence", Float),
    Column("evidence_source_span_id", uuid_type),
    Column("review_status", String),
    Column("extraction_method", String),
)
chunk_concepts = Table(
    "chunk_concepts",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("graph_version_id", uuid_type),
    Column("chunk_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("evidence_source_span_id", uuid_type),
    Column("confidence", Float),
    Column("extraction_method", String),
    Column("review_status", String),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)
attempts = Table(
    "attempts",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("attempt_type", String),
    Column("status", String),
    Column("idempotency_key", String),
    Column("payload", JSONB),
    Column("created_at", DateTime(timezone=True)),
)
evidence_ledger = Table(
    "evidence_ledger",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("attempt_id", uuid_type),
    Column("evidence_type", String),
    Column("value", Float),
    Column("confidence", Float),
    Column("idempotency_key", String),
)
mastery_states = Table(
    "mastery_states",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("self_confidence", Float),
    Column("diagnostic_status", String),
    Column("mastery", Float),
    Column("evidence_confidence", Float),
    Column("confidence_gap", Float),
    Column("misconception", Boolean),
    Column("evidence_ids", JSONB),
    Column("engine_version", String),
)
priority_snapshots = Table(
    "priority_snapshots",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("course_id", uuid_type),
    Column("evaluated_at", DateTime(timezone=True)),
    Column("exam_date", Date),
    Column("engine_version", String),
    Column("input_checksum", String),
    Column("created_at", DateTime(timezone=True)),
)
priority_items = Table(
    "priority_items",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("snapshot_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("priority_rank", Integer),
    Column("need", Float),
    Column("importance", Float),
    Column("urgency", Float),
    Column("reliability", Float),
    Column("priority_score", Float),
    Column("reasons", JSONB),
)
study_plans = Table(
    "study_plans",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("course_id", uuid_type),
    Column("priority_snapshot_id", uuid_type),
    Column("horizon_days", Integer),
    Column("daily_minutes", Integer),
    Column("planner_version", String),
    Column("input_checksum", String),
    Column("created_at", DateTime(timezone=True)),
)
study_plan_items = Table(
    "study_plan_items",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("plan_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("day_offset", Integer),
    Column("sequence", Integer),
    Column("activity", String),
    Column("duration_minutes", Integer),
    Column("expected_gain", Float),
    Column("decision_status", String),
    Column("reason", Text),
)
outbox_events = Table(
    "outbox_events",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("event_type", String),
    Column("aggregate_id", uuid_type),
    Column("payload", JSONB),
    Column("status", String),
    Column("attempts", Integer),
    Column("next_attempt_at", DateTime(timezone=True)),
    Column("dedupe_key", String),
    Column("locked_at", DateTime(timezone=True)),
    Column("locked_by", String),
    Column("last_error", Text),
    Column("processed_at", DateTime(timezone=True)),
)
chat_threads = Table(
    "chat_threads",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("status", String),
    Column("title", String),
    Column("initial_idempotency_key", String),
    Column("short_summary", Text),
    Column("summary_through_sequence", Integer),
    Column("next_sequence", Integer),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
    Column("last_message_at", DateTime(timezone=True)),
)
chat_messages = Table(
    "chat_messages",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("thread_id", uuid_type),
    Column("role", String),
    Column("sequence", Integer),
    Column("content", Text),
    Column("citations", JSONB),
    Column("metadata", JSONB),
    Column("idempotency_key", String),
    Column("created_at", DateTime(timezone=True)),
)
learning_events = Table(
    "learning_events",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("learner_id", uuid_type),
    Column("course_id", uuid_type),
    Column("thread_id", uuid_type),
    Column("attempt_id", uuid_type),
    Column("event_type", String),
    Column("payload", JSONB),
    Column("idempotency_key", String),
    Column("occurred_at", DateTime(timezone=True)),
    Column("created_at", DateTime(timezone=True)),
)
question_specs = Table(
    "question_specs",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("external_id", String),
    Column("blueprint_cell", JSONB),
    Column("concept_slugs", JSONB),
    Column("learning_objective", Text),
    Column("format", String),
    Column("cognitive_level", String),
    Column("difficulty_target", String),
    Column("misconception_target", Text),
    Column("required_evidence", Integer),
    Column("generation_count", Integer),
    Column("exposure_group", String),
    Column("state", String),
    Column("input_checksum", String),
    Column("created_at", DateTime(timezone=True)),
    Column("updated_at", DateTime(timezone=True)),
)
evidence_packs = Table(
    "evidence_packs",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("question_spec_id", uuid_type),
    Column("corpus_version", String),
    Column("retrieval_mode", String),
    Column("retrieval_trace", JSONB),
    Column("checksum", String),
    Column("state", String),
    Column("created_at", DateTime(timezone=True)),
)
evidence_pack_spans = Table(
    "evidence_pack_spans",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("evidence_pack_id", uuid_type),
    Column("source_span_id", uuid_type),
    Column("rank", Integer),
    Column("excerpt", Text),
)
question_candidates = Table(
    "question_candidates",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("course_id", uuid_type),
    Column("question_spec_id", uuid_type),
    Column("evidence_pack_id", uuid_type),
    Column("candidate_key", String),
    Column("format", String),
    Column("content", JSONB),
    Column("generator_metadata", JSONB),
    Column("state", String),
    Column("content_checksum", String),
    Column("created_at", DateTime(timezone=True)),
)
question_concepts = Table(
    "question_concepts",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("question_candidate_id", uuid_type),
    Column("concept_id", uuid_type),
    Column("role", String),
)
item_validations = Table(
    "item_validations",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("question_candidate_id", uuid_type),
    Column("validator_name", String),
    Column("validator_version", String),
    Column("status", String),
    Column("score", Float),
    Column("findings", JSONB),
    Column("input_checksum", String),
    Column("created_at", DateTime(timezone=True)),
)
review_decisions = Table(
    "review_decisions",
    metadata,
    Column("id", uuid_type, primary_key=True),
    Column("tenant_id", uuid_type),
    Column("question_candidate_id", uuid_type),
    Column("reviewer_id", uuid_type),
    Column("decision", String),
    Column("reason_code", String),
    Column("notes", Text),
    Column("created_at", DateTime(timezone=True)),
)
