"""Deterministic P0 contracts for evidence-grounded assessment authoring.

LLM calls are intentionally outside this module: candidates must pass the same
checks whether they were generated by Groq, written by an expert, or repaired.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from typing import Literal, Protocol

from pydantic import BaseModel, Field, model_validator

ObjectiveFormat = Literal["single_choice", "ordering_or_matching", "scenario_diagnosis"]
ConstructedFormat = Literal[
    "code_or_pseudocode",
    "system_design",
    "tracing_and_monitoring_diagnosis",
    "security_and_data_governance",
    "guardrail_or_incident_reasoning",
]


class QuestionSpec(BaseModel):
    spec_id: str = Field(pattern=r"^qs-[a-z0-9-]+$")
    course_id: str
    concept_ids: list[str] = Field(min_length=1)
    learning_objective: str = Field(min_length=12)
    scope: str
    format: ObjectiveFormat | ConstructedFormat
    cognitive_level: Literal["recall", "understand", "apply", "analyze"]
    difficulty_target: Literal["easy", "medium", "hard"]
    misconception_target: str = Field(min_length=8)
    required_evidence: int = Field(default=1, ge=1, le=5)
    generation_count: int = Field(default=1, ge=1, le=5)
    exposure_group: str

    @property
    def is_constructed_response(self) -> bool:
        return self.format not in {
            "single_choice",
            "ordering_or_matching",
            "scenario_diagnosis",
        }


class EvidenceSpan(BaseModel):
    source_span_id: str
    document_title: str = Field(min_length=1)
    locator: str = Field(min_length=1)
    excerpt: str = Field(min_length=24)
    rank: int = Field(ge=1)


class EvidencePack(BaseModel):
    spec_id: str
    tenant_id: str
    course_id: str
    corpus_version: str
    retrieval_mode: str
    spans: list[EvidenceSpan] = Field(min_length=1, max_length=5)

    @model_validator(mode="after")
    def unique_spans(self) -> EvidencePack:
        ids = [span.source_span_id for span in self.spans]
        if len(ids) != len(set(ids)):
            raise ValueError("Evidence packs must not repeat a source span")
        return self

    @property
    def checksum(self) -> str:
        material = "|".join(
            [self.spec_id, self.corpus_version]
            + [f"{span.source_span_id}:{span.excerpt}" for span in self.spans]
        )
        return sha256(material.encode("utf-8")).hexdigest()


class Option(BaseModel):
    id: str = Field(pattern=r"^[A-Z]$")
    text: str = Field(min_length=2)
    misconception: str = Field(min_length=3)


class ClaimEvidence(BaseModel):
    claim: str = Field(min_length=4)
    source_span_ids: list[str] = Field(min_length=1)


class RubricCriterion(BaseModel):
    id: str = Field(pattern=r"^[a-z0-9_-]+$")
    label: str = Field(min_length=3)
    max_score: int = Field(ge=1, le=10)
    observable_evidence: list[str] = Field(min_length=1)
    common_failure_modes: list[str] = Field(min_length=1)


class QuestionCandidate(BaseModel):
    candidate_id: str = Field(pattern=r"^qc-[a-z0-9-]+$")
    spec_id: str
    format: ObjectiveFormat | ConstructedFormat
    stem: str = Field(min_length=20)
    options: list[Option] = Field(default_factory=list)
    correct_option_ids: list[str] = Field(default_factory=list)
    rationale: str = Field(min_length=12)
    claim_to_evidence: list[ClaimEvidence] = Field(min_length=1)
    difficulty_rationale: str = Field(min_length=8)
    rubric: list[RubricCriterion] = Field(default_factory=list)
    acceptable_alternatives: list[str] = Field(default_factory=list)


@dataclass(frozen=True)
class ValidationFinding:
    rule: str
    message: str
    severity: Literal["error", "warning"]


@dataclass(frozen=True)
class ValidationResult:
    passed: bool
    findings: tuple[ValidationFinding, ...]

    @property
    def errors(self) -> tuple[ValidationFinding, ...]:
        return tuple(item for item in self.findings if item.severity == "error")


def validate_candidate(spec: QuestionSpec, pack: EvidencePack, candidate: QuestionCandidate) -> ValidationResult:
    findings: list[ValidationFinding] = []
    if candidate.spec_id != spec.spec_id:
        findings.append(ValidationFinding("spec_match", "Candidate belongs to another spec", "error"))
    if candidate.format != spec.format:
        findings.append(ValidationFinding("format_match", "Candidate format differs from spec", "error"))

    evidence_ids = {span.source_span_id for span in pack.spans}
    referenced_ids = {source for claim in candidate.claim_to_evidence for source in claim.source_span_ids}
    if not referenced_ids:
        findings.append(ValidationFinding("evidence_required", "No source span is referenced", "error"))
    if not referenced_ids.issubset(evidence_ids):
        findings.append(ValidationFinding("evidence_scope", "Candidate cites a span outside its evidence pack", "error"))
    if len(referenced_ids) < spec.required_evidence:
        findings.append(ValidationFinding("evidence_count", "Insufficient cited source spans", "error"))

    if spec.is_constructed_response:
        if candidate.options or candidate.correct_option_ids:
            findings.append(ValidationFinding("cr_no_options", "Constructed response cannot carry options", "error"))
        if not candidate.rubric:
            findings.append(ValidationFinding("cr_rubric", "Constructed response needs a rubric", "error"))
        if not candidate.acceptable_alternatives:
            findings.append(ValidationFinding("cr_alternatives", "Constructed response needs alternatives", "error"))
    else:
        option_ids = [option.id for option in candidate.options]
        if len(option_ids) != 4:
            findings.append(ValidationFinding("objective_option_count", "Objective item needs exactly four options", "error"))
        if option_ids != ["A", "B", "C", "D"]:
            findings.append(ValidationFinding("objective_option_labels", "Objective options must be ordered A through D", "error"))
        if len(option_ids) != len(set(option_ids)):
            findings.append(ValidationFinding("objective_unique_options", "Option IDs must be unique", "error"))
        if any(not option.misconception.strip() for option in candidate.options):
            findings.append(ValidationFinding("distractor_misconception", "Every option needs authoring rationale", "error"))
        correct = set(candidate.correct_option_ids)
        if not correct or not correct.issubset(set(option_ids)):
            findings.append(ValidationFinding("objective_answer_key", "Answer key must reference options", "error"))
        if len(correct) != 1:
            findings.append(ValidationFinding("objective_exactly_one", "Every objective format requires exactly one correct option", "error"))
        normalized = [" ".join(option.text.casefold().split()) for option in candidate.options]
        if len(normalized) != len(set(normalized)):
            findings.append(ValidationFinding("objective_duplicate_text", "Options must not be duplicates", "error"))

    return ValidationResult(
        passed=not any(item.severity == "error" for item in findings), findings=tuple(findings)
    )


class Retriever(Protocol):
    def retrieve(self, query: str, **scope: str | int) -> dict: ...


def build_evidence_pack(
    spec: QuestionSpec,
    *,
    tenant_id: str,
    course_id: str,
    corpus_version: str,
    retriever: Retriever,
) -> EvidencePack:
    """Snapshot the current retrieval result; never re-retrieve during review."""
    query = f"{spec.learning_objective}. {spec.misconception_target}"
    result = retriever.retrieve(
        query,
        tenant_id=tenant_id,
        course_id=course_id,
        candidate_limit=12,
        limit=max(spec.required_evidence, 3),
    )
    spans: list[EvidenceSpan] = []
    seen: set[str] = set()
    for hit in result.get("hits", []):
        payload = hit.get("payload") or {}
        source_span_id = str(payload.get("source_span_id") or "")
        excerpt = str(payload.get("content") or "").strip()
        if not source_span_id or not excerpt or source_span_id in seen:
            continue
        seen.add(source_span_id)
        locator = payload.get("locator") or payload.get("ordinal") or "corpus"
        spans.append(
            EvidenceSpan(
                source_span_id=source_span_id,
                document_title=str(payload.get("document_title") or "Untitled source"),
                locator=str(locator),
                excerpt=excerpt,
                rank=len(spans) + 1,
            )
        )
        if len(spans) == 5:
            break
    if len(spans) < spec.required_evidence:
        raise ValueError(f"Evidence retrieval returned {len(spans)} spans; spec requires {spec.required_evidence}")
    return EvidencePack(
        spec_id=spec.spec_id,
        tenant_id=tenant_id,
        course_id=course_id,
        corpus_version=corpus_version,
        retrieval_mode=str(result.get("retrieval_mode", "hybrid")),
        spans=spans,
    )
